CREATE DATABASE java_web;
USE java_web;
CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    DEPARTMENT_CODE VARCHAR(10) NOT NULL UNIQUE,
    DEPARTMENT_NAME VARCHAR(100) NOT NULL
);
CREATE TABLE STAFF (
    STAFF_ID INT AUTO_INCREMENT PRIMARY KEY,
    STAFF_CODE VARCHAR(20) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100),
    ROLE VARCHAR(50),  -- 'ADMIN', 'DIRECTOR', 'PROFESSOR', 'ASSOCIATE_PROFESSOR', 'ASSISTANT_PROFESSOR'
    DEPARTMENT_CODE VARCHAR(10) NOT NULL,
    FOREIGN KEY (DEPARTMENT_CODE) REFERENCES DEPARTMENTS(DEPARTMENT_CODE)
);
CREATE TABLE ADMINS (
    ADMIN_ID INT AUTO_INCREMENT PRIMARY KEY,
    STAFF_CODE VARCHAR(20) NOT NULL UNIQUE,
    PASSWORD VARCHAR(60) NOT NULL,
    FOREIGN KEY (STAFF_CODE) REFERENCES STAFF(STAFF_CODE)
);
CREATE TABLE STUDENTS (
    STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROLL_NUMBER VARCHAR(20) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100),
    JOINING_YEAR SMALLINT NOT NULL CHECK (joining_year BETWEEN 2000 AND 3000),
    DEPARTMENT_CODE VARCHAR(10) NOT NULL,
    FOREIGN KEY (DEPARTMENT_CODE) REFERENCES DEPARTMENTS(DEPARTMENT_CODE)
);
